# .github/workflows/deploy-databricks.yml
name: Deploy Databricks Bundle

on:
  push:
    branches: 
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # Setup Databricks CLI credentials for v2+ (unified auth)
      - name: Configure Databricks CLI credentials
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Validate Databricks Bundle
        run: databricks bundle validate

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy --target ${{ github.event.inputs.environment || 'dev' }} --force-lock
