name: Databricks CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment
        options:
          - dev
          - qa
          - prod

jobs:
  build-and-deploy:
    name: Build & Deploy (${{ github.event.inputs.environment || 'dev' }})
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run unit tests
        run: pytest tests/

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: pipaa
        run: echo ${{ github.event.inputs.environment }}

      - name: Validate Databricks Bundle
        run: databricks bundle validate

        
      - name: Deploy Databricks Bundle
        run: databricks bundle deploy --target ${{ github.event.inputs.environment || 'dev' }}

      - name: Run Smoke Tests
        run: python scripts/smoke_tests.py

      - name: Log deployment success
        if: success()
        run: echo "Deployment completed successfully for ${{ github.event.inputs.environment || 'dev' }} at $(date)"

      - name: Log deployment failure
        if: failure()
        run: echo "Deployment failed for ${{ github.event.inputs.environment || 'dev' }} at $(date)"
 
